In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../datasets/P_Data_Extract_From_World_Development_Indicators/0bcc63a9-526c-4673-98ef-4f8ebcf0fe7c_Data.csv')

In [4]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,..,..,..,..,..,..,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,..
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,..,..,..,..,..,..,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,..
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,..,..,..,..,..,..,...,78,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85,..
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,..,..,..,..,..,..,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,..
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,..,..,..,..,..,..,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,..

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24211 entries, 0 to 24210
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   24208 non-null  object
 1   Country Code   24206 non-null  object
 2   Series Name    24206 non-null  object
 3   Series Code    24206 non-null  object
 4   1989 [YR1989]  24206 non-null  object
 5   1990 [YR1990]  24206 non-null  object
 6   1991 [YR1991]  24206 non-null  object
 7   1992 [YR1992]  24206 non-null  object
 8   1993 [YR1993]  24206 non-null  object
 9   1994 [YR1994]  24206 non-null  object
 10  1995 [YR1995]  24206 non-null  object
 11  1996 [YR1996]  24206 non-null  object
 12  1997 [YR1997]  24206 non-null  object
 13  1998 [YR1998]  24206 non-null  object
 14  1999 [YR1999]  24206 non-null  object
 15  2000 [YR2000]  24206 non-null  object
 16  2001 [YR2001]  24206 non-null  object
 17  2002 [YR2002]  24206 non-null  object
 18  2003 [YR2003]  24206 non-null  object
 19  2004 [YR2004]  24206 non-null  object
 20  2005 [YR2005]  24206 non-null  object
 21  2006 [YR2006]  24206 non-null  object
 22  2007 [YR2007]  24206 non-null  object
 23  2008 [YR2008]  24206 non-null  object
 24  2009 [YR2009]  24206 non-null  object
 25  2010 [YR2010]  24206 non-null  object
 26  2011 [YR2011]  24206 non-null  object
 27  2012 [YR2012]  24206 non-null  object
 28  2013 [YR2013]  24206 non-null  object
 29  2014 [YR2014]  24206 non-null  object
 30  2015 [YR2015]  24206 non-null  object
 31  2016 [YR2016]  24206 non-null  object
 32  2017 [YR2017]  24206 non-null  object
 33  2018 [YR2018]  24206 non-null  object
 34  2019 [YR2019]  24206 non-null  object
 35  2020 [YR2020]  24206 non-null  object
 36  2021 [YR2021]  24206 non-null  object
 37  2022 [YR2022]  24206 non-null  object
 38  2023 [YR2023]  24206 non-null  object
dtypes: object(39)
memory usage: 7.2+ MB

In [6]:
df.shape

(24211, 39)

In [7]:
df.isnull().sum()

Country Name     3
Country Code     5
Series Name      5
Series Code      5
1989 [YR1989]    5
1990 [YR1990]    5
1991 [YR1991]    5
1992 [YR1992]    5
1993 [YR1993]    5
1994 [YR1994]    5
1995 [YR1995]    5
1996 [YR1996]    5
1997 [YR1997]    5
1998 [YR1998]    5
1999 [YR1999]    5
2000 [YR2000]    5
2001 [YR2001]    5
2002 [YR2002]    5
2003 [YR2003]    5
2004 [YR2004]    5
2005 [YR2005]    5
2006 [YR2006]    5
2007 [YR2007]    5
2008 [YR2008]    5
2009 [YR2009]    5
2010 [YR2010]    5
2011 [YR2011]    5
2012 [YR2012]    5
2013 [YR2013]    5
2014 [YR2014]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
dtype: int64

In [8]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]', '1992 [YR1992]',
       '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]',
       '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]',
       '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]',
       '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]',
       '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]',
       '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [9]:
series_name = df['Series Name'].value_counts()

print(series_name)

Series Name
Access to clean fuels and technologies for cooking (% of population)     266
Methane (CH4) emissions from Waste (Mt CO2e)                             266
Methane (CH4) emissions from Power Industry (Energy) (Mt CO2e)           266
Methane (CH4) emissions from Industrial Processes (Mt CO2e)              266
Methane (CH4) emissions from Industrial Combustion (Energy) (Mt CO2e)    266
                                                                        ...
Electric power transmission and distribution losses (% of output)        266
Electric power consumption (kWh per capita)                              266
Combustible renewables and waste (% of total energy)                     266
Carbon intensity of GDP (kg CO2e per constant 2015 US$ of GDP)           266
Total greenhouse gas emissions including LULUCF (Mt CO2e)                266
Name: count, Length: 91, dtype: int64

In [10]:
df['Country Name'].value_counts()

Country Name
Afghanistan                                         91
St. Martin (French part)                            91
Seychelles                                          91
Sierra Leone                                        91
Singapore                                           91
                                                    ..
Israel                                              91
Italy                                               91
Jamaica                                             91
Data from database: World Development Indicators     1
Last Updated: 01/28/2025                             1
Name: count, Length: 268, dtype: int64

In [11]:
df.replace("..", pd.NA, inplace=True)

In [12]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,<NA>
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,<NA>
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,78,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85,<NA>
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,<NA>
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,<NA>

In [13]:
df.isnull().sum()

Country Name         3
Country Code         5
Series Name          5
Series Code          5
1989 [YR1989]    12615
1990 [YR1990]     9273
1991 [YR1991]     8941
1992 [YR1992]     8805
1993 [YR1993]     8734
1994 [YR1994]     8646
1995 [YR1995]     7713
1996 [YR1996]     8242
1997 [YR1997]     8189
1998 [YR1998]     8116
1999 [YR1999]     8081
2000 [YR2000]     4682
2001 [YR2001]     5360
2002 [YR2002]     5316
2003 [YR2003]     5225
2004 [YR2004]     5042
2005 [YR2005]     4187
2006 [YR2006]     4989
2007 [YR2007]     4905
2008 [YR2008]     5020
2009 [YR2009]     4973
2010 [YR2010]     4134
2011 [YR2011]     4062
2012 [YR2012]     4042
2013 [YR2013]     4019
2014 [YR2014]     4045
2015 [YR2015]     5562
2016 [YR2016]     7580
2017 [YR2017]     7584
2018 [YR2018]     8403
2019 [YR2019]     8417
2020 [YR2020]     8432
2021 [YR2021]    10105
2022 [YR2022]    10396
2023 [YR2023]    12629
dtype: int64

In [14]:
# Selecting only year columns
year_columns = df.columns[4:]
df[year_columns] = df[year_columns].apply(pd.to_numeric, errors='coerce')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24211 entries, 0 to 24210
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   24208 non-null  object
 1   Country Code   24206 non-null  object
 2   Series Name    24206 non-null  object
 3   Series Code    24206 non-null  object
 4   1989 [YR1989]  11596 non-null  float64
 5   1990 [YR1990]  14938 non-null  float64
 6   1991 [YR1991]  15270 non-null  float64
 7   1992 [YR1992]  15406 non-null  float64
 8   1993 [YR1993]  15477 non-null  float64
 9   1994 [YR1994]  15565 non-null  float64
 10  1995 [YR1995]  16498 non-null  float64
 11  1996 [YR1996]  15969 non-null  float64
 12  1997 [YR1997]  16022 non-null  float64
 13  1998 [YR1998]  16095 non-null  float64
 14  1999 [YR1999]  16130 non-null  float64
 15  2000 [YR2000]  19529 non-null  float64
 16  2001 [YR2001]  18851 non-null  float64
 17  2002 [YR2002]  18895 non-null  float64
 18  2003 [YR2003]  18986 non-null  float64
 19  2004 [YR2004]  19169 non-null  float64
 20  2005 [YR2005]  20024 non-null  float64
 21  2006 [YR2006]  19222 non-null  float64
 22  2007 [YR2007]  19306 non-null  float64
 23  2008 [YR2008]  19191 non-null  float64
 24  2009 [YR2009]  19238 non-null  float64
 25  2010 [YR2010]  20077 non-null  float64
 26  2011 [YR2011]  20149 non-null  float64
 27  2012 [YR2012]  20169 non-null  float64
 28  2013 [YR2013]  20192 non-null  float64
 29  2014 [YR2014]  20166 non-null  float64
 30  2015 [YR2015]  18649 non-null  float64
 31  2016 [YR2016]  16631 non-null  float64
 32  2017 [YR2017]  16627 non-null  float64
 33  2018 [YR2018]  15808 non-null  float64
 34  2019 [YR2019]  15794 non-null  float64
 35  2020 [YR2020]  15779 non-null  float64
 36  2021 [YR2021]  14106 non-null  float64
 37  2022 [YR2022]  13815 non-null  float64
 38  2023 [YR2023]  11582 non-null  float64
dtypes: float64(35), object(4)
memory usage: 7.2+ MB

In [16]:
df[year_columns] = df.groupby(["Country Name", "Series Name"])[year_columns].ffill()
df[year_columns] = df.groupby(["Country Name", "Series Name"])[year_columns].bfill()

In [17]:
df.isnull().sum()

Country Name         3
Country Code         5
Series Name          5
Series Code          5
1989 [YR1989]    12615
1990 [YR1990]     9273
1991 [YR1991]     8941
1992 [YR1992]     8805
1993 [YR1993]     8734
1994 [YR1994]     8646
1995 [YR1995]     7713
1996 [YR1996]     8242
1997 [YR1997]     8189
1998 [YR1998]     8116
1999 [YR1999]     8081
2000 [YR2000]     4682
2001 [YR2001]     5360
2002 [YR2002]     5316
2003 [YR2003]     5225
2004 [YR2004]     5042
2005 [YR2005]     4187
2006 [YR2006]     4989
2007 [YR2007]     4905
2008 [YR2008]     5020
2009 [YR2009]     4973
2010 [YR2010]     4134
2011 [YR2011]     4062
2012 [YR2012]     4042
2013 [YR2013]     4019
2014 [YR2014]     4045
2015 [YR2015]     5562
2016 [YR2016]     7580
2017 [YR2017]     7584
2018 [YR2018]     8403
2019 [YR2019]     8417
2020 [YR2020]     8432
2021 [YR2021]    10105
2022 [YR2022]    10396
2023 [YR2023]    12629
dtype: int64

In [18]:
missing_threshold = 0.5 * len(year_columns)
df = df.dropna(thresh=missing_threshold, axis=0)

In [19]:
df.shape

(19243, 39)

In [20]:
df[year_columns] = df[year_columns].apply(lambda x: x.fillna(x.mean()), axis=0)

In [21]:
df.isnull().sum()

Country Name     0
Country Code     0
Series Name      0
Series Code      0
1989 [YR1989]    0
1990 [YR1990]    0
1991 [YR1991]    0
1992 [YR1992]    0
1993 [YR1993]    0
1994 [YR1994]    0
1995 [YR1995]    0
1996 [YR1996]    0
1997 [YR1997]    0
1998 [YR1998]    0
1999 [YR1999]    0
2000 [YR2000]    0
2001 [YR2001]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
dtype: int64

In [22]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,154.506541
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,154.506541
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,154.506541
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,154.506541
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,154.506541

In [23]:
df.columns = [col.replace(" [YR", "_").replace("]", "") if "YR" in col else col for col in df.columns]

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989_1989,1990_1990,1991_1991,1992_1992,1993_1993,1994_1994,...,2014_2014,2015_2015,2016_2016,2017_2017,2018_2018,2019_2019,2020_2020,2021_2021,2022_2022,2023_2023
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,154.506541
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,154.506541
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,154.506541
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,154.506541
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,7.707894e+07,7.737844e+07,5.953423e+07,6.544516e+07,6.746293e+07,7.090160e+07,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,154.506541

In [26]:
df.shape

(19243, 39)

In [27]:
df.to_csv('../datasets/cleaned_dataset.csv')

In [28]:
# World Bank, 2025
# World Bank country classifications by income level for 2024-2025
# https://databank.worldbank.org/data/download/site-content/CLASS.xlsx

url = "https://databank.worldbank.org/data/download/site-content/CLASS.xlsx"

column_names = ["Country Name", "Country Code", "Region", "Income Level", "Lending Category", "Extra"]

income_df = pd.read_excel(url, sheet_name="List of economies", skiprows=3, header=None,  names=column_names)

URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

In [ ]:
income_df.head(100)

In [ ]:
income_df = income_df[["Country Name", "Country Code", "Income Level"]]

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df = df.merge(income_df, on=["Country Name", "Country Code"], how="left")

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.head()

In [ ]:
print(growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].value_counts())

In [ ]:
missing_countries = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()]["Country Name"].unique()
print("Countries with missing income classification:", missing_countries)

In [ ]:
regions_to_remove = [
    "World", "Sub-Saharan Africa", "OECD members", "East Asia & Pacific", "Europe & Central Asia",
    "Middle East & North Africa", "Latin America & Caribbean", "South Asia", "North America",
    "Fragile and conflict affected situations", "Least developed countries: UN classification",
    "Low & middle income", "Lower middle income", "Middle income", "Upper middle income",
    "Heavily indebted poor countries (HIPC)", "Small states", "IBRD only", "IDA & IBRD total",
    "IDA blend", "IDA only", "IDA total", "Euro area", "European Union",
    "East Asia & Pacific (IDA & IBRD countries)", "Europe & Central Asia (IDA & IBRD countries)",
    "Latin America & the Caribbean (IDA & IBRD countries)",
    "Middle East & North Africa (IDA & IBRD countries)", "Sub-Saharan Africa (IDA & IBRD countries)",
    "Africa Eastern and Southern", "Africa Western and Central", "Arab World", "Caribbean small states",
    "Central Europe and the Baltics", "Early-demographic dividend", "East Asia & Pacific (excluding high income)",
    "Europe & Central Asia (excluding high income)", "High income", "Late-demographic dividend",
    "Latin America & Caribbean (excluding high income)", "Low income", "Middle East & North Africa (excluding high income)",
    "Other small states", "Pacific island small states", "Post-demographic dividend",
    "Pre-demographic dividend", "South Asia (IDA & IBRD)", "Sub-Saharan Africa (excluding high income)"
]

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].isin(regions_to_remove)
]

print("Remaining unique countries:", growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].nunique())

In [ ]:
missing_countries = growth_rates_emissions_energy_prod_income_level_country_df[
    growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()
]["Country Name"].unique()

print("Low/Middle-Income Countries with Missing Income Classification:", missing_countries)

In [ ]:
manual_income_levels = {
    "Cote d'Ivoire": "Lower middle income",
    "Sao Tome and Principe": "Lower middle income",
    "Turkiye": "Upper middle income",
    "Viet Nam": "Lower middle income",
    "Afghanistan": "Low income",
    "Venezuela, RB": "Not classified",
    "Aruba": "High income",
    "Curacao": "High income",
    "Czechia": "Not classified"   
}

growth_rates_emissions_energy_prod_income_level_country_df["Income Level"] = growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].map(manual_income_levels).fillna(growth_rates_emissions_energy_prod_income_level_country_df["Income Level"])

missing_countries_final = growth_rates_emissions_energy_prod_income_level_country_df[
    growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()
]["Country Name"].unique()

print("Final missing countries:", missing_countries_final)

In [ ]:
# Remove High income countries

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isin(["High income", "Not classified"])
]

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.tail()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df['Income Level'].value_counts()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.shape

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.info()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.isnull().sum()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df['Income Level'].value_counts()

In [ ]:
unique_country_count = growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].nunique()
print(f"Final unique country count: {unique_country_count}")

In [ ]:
duplicates = growth_rates_emissions_energy_prod_income_level_country_df.duplicated()
assert duplicates.sum() == 0, f"Found {duplicates.sum()} duplicate rows!"
print("No duplicate rows found.")

In [ ]:
valid_income_levels = ["Low income", "Lower middle income", "Upper middle income"]
unique_income_levels = growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].unique()

assert all(income in valid_income_levels for income in unique_income_levels), "There are invalid income levels in the dataset!"
print("Only low, lower middle, and upper middle income countries remain.")

In [ ]:
country_check = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].isin(["Bulgaria", "Palau", "Russian Federation"])]

country_check.tail()

In [ ]:
# This year, three countries—Bulgaria, Palau, and Russia—moved from the upper-middle-income to the high-income category (World Bank, 2025)
# World Bank country classifications by income level for 2024-2025
# https://blogs.worldbank.org/en/opendata/world-bank-country-classifications-by-income-level-for-2024-2025
# Remove Bulgaria, Palau, Russian Federation

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].isin(["Bulgaria", "Palau", "Russian Federation"])
]

In [ ]:
country_check = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].isin(["Bulgaria", "Palau", "Russian Federation"])]

country_check.head()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.shape

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.isnull().sum()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.info()

In [ ]:
growth_rates_emissions_energy_prod_income_level_country_df.to_csv('../datasets/growth_rates_emissions_energy_prod_income_level_country_df.csv')

print("Merged Dataset with only Low, Lower middle, Upper income level countries saved successfully")