In [608]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [609]:
df = pd.read_csv('../datasets/P_Data_Extract_From_World_Development_Indicators/0bcc63a9-526c-4673-98ef-4f8ebcf0fe7c_Data.csv')

In [610]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,..,..,..,..,..,..,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,..
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,..,..,..,..,..,..,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,..
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,..,..,..,..,..,..,...,78,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85,..
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,..,..,..,..,..,..,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,..
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,..,..,..,..,..,..,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,..

In [611]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24211 entries, 0 to 24210
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   24208 non-null  object
 1   Country Code   24206 non-null  object
 2   Series Name    24206 non-null  object
 3   Series Code    24206 non-null  object
 4   1989 [YR1989]  24206 non-null  object
 5   1990 [YR1990]  24206 non-null  object
 6   1991 [YR1991]  24206 non-null  object
 7   1992 [YR1992]  24206 non-null  object
 8   1993 [YR1993]  24206 non-null  object
 9   1994 [YR1994]  24206 non-null  object
 10  1995 [YR1995]  24206 non-null  object
 11  1996 [YR1996]  24206 non-null  object
 12  1997 [YR1997]  24206 non-null  object
 13  1998 [YR1998]  24206 non-null  object
 14  1999 [YR1999]  24206 non-null  object
 15  2000 [YR2000]  24206 non-null  object
 16  2001 [YR2001]  24206 non-null  object
 17  2002 [YR2002]  24206 non-null  object
 18  2003 [YR2003]  24206 non-null  object
 19  2004 [YR2004]  24206 non-null  object
 20  2005 [YR2005]  24206 non-null  object
 21  2006 [YR2006]  24206 non-null  object
 22  2007 [YR2007]  24206 non-null  object
 23  2008 [YR2008]  24206 non-null  object
 24  2009 [YR2009]  24206 non-null  object
 25  2010 [YR2010]  24206 non-null  object
 26  2011 [YR2011]  24206 non-null  object
 27  2012 [YR2012]  24206 non-null  object
 28  2013 [YR2013]  24206 non-null  object
 29  2014 [YR2014]  24206 non-null  object
 30  2015 [YR2015]  24206 non-null  object
 31  2016 [YR2016]  24206 non-null  object
 32  2017 [YR2017]  24206 non-null  object
 33  2018 [YR2018]  24206 non-null  object
 34  2019 [YR2019]  24206 non-null  object
 35  2020 [YR2020]  24206 non-null  object
 36  2021 [YR2021]  24206 non-null  object
 37  2022 [YR2022]  24206 non-null  object
 38  2023 [YR2023]  24206 non-null  object
dtypes: object(39)
memory usage: 7.2+ MB

In [612]:
df.shape

(24211, 39)

In [613]:
df.isnull().sum()

Country Name     3
Country Code     5
Series Name      5
Series Code      5
1989 [YR1989]    5
1990 [YR1990]    5
1991 [YR1991]    5
1992 [YR1992]    5
1993 [YR1993]    5
1994 [YR1994]    5
1995 [YR1995]    5
1996 [YR1996]    5
1997 [YR1997]    5
1998 [YR1998]    5
1999 [YR1999]    5
2000 [YR2000]    5
2001 [YR2001]    5
2002 [YR2002]    5
2003 [YR2003]    5
2004 [YR2004]    5
2005 [YR2005]    5
2006 [YR2006]    5
2007 [YR2007]    5
2008 [YR2008]    5
2009 [YR2009]    5
2010 [YR2010]    5
2011 [YR2011]    5
2012 [YR2012]    5
2013 [YR2013]    5
2014 [YR2014]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
dtype: int64

In [614]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '1989 [YR1989]', '1990 [YR1990]', '1991 [YR1991]', '1992 [YR1992]',
       '1993 [YR1993]', '1994 [YR1994]', '1995 [YR1995]', '1996 [YR1996]',
       '1997 [YR1997]', '1998 [YR1998]', '1999 [YR1999]', '2000 [YR2000]',
       '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]',
       '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]',
       '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]',
       '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [615]:
series_name = df['Series Name'].value_counts()

print(series_name)

Series Name
Access to clean fuels and technologies for cooking (% of population)     266
Methane (CH4) emissions from Waste (Mt CO2e)                             266
Methane (CH4) emissions from Power Industry (Energy) (Mt CO2e)           266
Methane (CH4) emissions from Industrial Processes (Mt CO2e)              266
Methane (CH4) emissions from Industrial Combustion (Energy) (Mt CO2e)    266
                                                                        ...
Electric power transmission and distribution losses (% of output)        266
Electric power consumption (kWh per capita)                              266
Combustible renewables and waste (% of total energy)                     266
Carbon intensity of GDP (kg CO2e per constant 2015 US$ of GDP)           266
Total greenhouse gas emissions including LULUCF (Mt CO2e)                266
Name: count, Length: 91, dtype: int64

In [616]:
df['Country Name'].value_counts()

Country Name
Afghanistan                                         91
St. Martin (French part)                            91
Seychelles                                          91
Sierra Leone                                        91
Singapore                                           91
                                                    ..
Israel                                              91
Italy                                               91
Jamaica                                             91
Data from database: World Development Indicators     1
Last Updated: 01/28/2025                             1
Name: count, Length: 268, dtype: int64

In [617]:
df.replace("..", pd.NA, inplace=True)

In [618]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,<NA>
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,<NA>
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,78,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85,<NA>
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,<NA>
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,<NA>

In [619]:
df.isnull().sum()

Country Name         3
Country Code         5
Series Name          5
Series Code          5
1989 [YR1989]    12615
1990 [YR1990]     9273
1991 [YR1991]     8941
1992 [YR1992]     8805
1993 [YR1993]     8734
1994 [YR1994]     8646
1995 [YR1995]     7713
1996 [YR1996]     8242
1997 [YR1997]     8189
1998 [YR1998]     8116
1999 [YR1999]     8081
2000 [YR2000]     4682
2001 [YR2001]     5360
2002 [YR2002]     5316
2003 [YR2003]     5225
2004 [YR2004]     5042
2005 [YR2005]     4187
2006 [YR2006]     4989
2007 [YR2007]     4905
2008 [YR2008]     5020
2009 [YR2009]     4973
2010 [YR2010]     4134
2011 [YR2011]     4062
2012 [YR2012]     4042
2013 [YR2013]     4019
2014 [YR2014]     4045
2015 [YR2015]     5562
2016 [YR2016]     7580
2017 [YR2017]     7584
2018 [YR2018]     8403
2019 [YR2019]     8417
2020 [YR2020]     8432
2021 [YR2021]    10105
2022 [YR2022]    10396
2023 [YR2023]    12629
dtype: int64

In [620]:
# Selecting only year columns
year_columns = df.columns[4:]
df[year_columns] = df[year_columns].apply(pd.to_numeric, errors='coerce')

In [621]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24211 entries, 0 to 24210
Data columns (total 39 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   24208 non-null  object
 1   Country Code   24206 non-null  object
 2   Series Name    24206 non-null  object
 3   Series Code    24206 non-null  object
 4   1989 [YR1989]  11596 non-null  float64
 5   1990 [YR1990]  14938 non-null  float64
 6   1991 [YR1991]  15270 non-null  float64
 7   1992 [YR1992]  15406 non-null  float64
 8   1993 [YR1993]  15477 non-null  float64
 9   1994 [YR1994]  15565 non-null  float64
 10  1995 [YR1995]  16498 non-null  float64
 11  1996 [YR1996]  15969 non-null  float64
 12  1997 [YR1997]  16022 non-null  float64
 13  1998 [YR1998]  16095 non-null  float64
 14  1999 [YR1999]  16130 non-null  float64
 15  2000 [YR2000]  19529 non-null  float64
 16  2001 [YR2001]  18851 non-null  float64
 17  2002 [YR2002]  18895 non-null  float64
 18  2003 [YR2003]  18986 non-null  float64
 19  2004 [YR2004]  19169 non-null  float64
 20  2005 [YR2005]  20024 non-null  float64
 21  2006 [YR2006]  19222 non-null  float64
 22  2007 [YR2007]  19306 non-null  float64
 23  2008 [YR2008]  19191 non-null  float64
 24  2009 [YR2009]  19238 non-null  float64
 25  2010 [YR2010]  20077 non-null  float64
 26  2011 [YR2011]  20149 non-null  float64
 27  2012 [YR2012]  20169 non-null  float64
 28  2013 [YR2013]  20192 non-null  float64
 29  2014 [YR2014]  20166 non-null  float64
 30  2015 [YR2015]  18649 non-null  float64
 31  2016 [YR2016]  16631 non-null  float64
 32  2017 [YR2017]  16627 non-null  float64
 33  2018 [YR2018]  15808 non-null  float64
 34  2019 [YR2019]  15794 non-null  float64
 35  2020 [YR2020]  15779 non-null  float64
 36  2021 [YR2021]  14106 non-null  float64
 37  2022 [YR2022]  13815 non-null  float64
 38  2023 [YR2023]  11582 non-null  float64
dtypes: float64(35), object(4)
memory usage: 7.2+ MB

In [622]:
df[year_columns] = df.groupby(["Country Name", "Series Name"])[year_columns].transform(lambda x: x.bfill().ffill())

In [623]:
df["2023 [YR2023]"] = df["2023 [YR2023]"].where(df["2023 [YR2023]"] < df["2022 [YR2022]"] * 1.5, df["2022 [YR2022]"])

In [624]:
df.isnull().sum()

Country Name         3
Country Code         5
Series Name          5
Series Code          5
1989 [YR1989]    12615
1990 [YR1990]     9273
1991 [YR1991]     8941
1992 [YR1992]     8805
1993 [YR1993]     8734
1994 [YR1994]     8646
1995 [YR1995]     7713
1996 [YR1996]     8242
1997 [YR1997]     8189
1998 [YR1998]     8116
1999 [YR1999]     8081
2000 [YR2000]     4682
2001 [YR2001]     5360
2002 [YR2002]     5316
2003 [YR2003]     5225
2004 [YR2004]     5042
2005 [YR2005]     4187
2006 [YR2006]     4989
2007 [YR2007]     4905
2008 [YR2008]     5020
2009 [YR2009]     4973
2010 [YR2010]     4134
2011 [YR2011]     4062
2012 [YR2012]     4042
2013 [YR2013]     4019
2014 [YR2014]     4045
2015 [YR2015]     5562
2016 [YR2016]     7580
2017 [YR2017]     7584
2018 [YR2018]     8403
2019 [YR2019]     8417
2020 [YR2020]     8432
2021 [YR2021]    10105
2022 [YR2022]    10396
2023 [YR2023]    10396
dtype: int64

In [625]:
# df[year_columns] = df.groupby(["Country Name", "Series Name"])[year_columns].transform(lambda x: x.fillna(x.mean()))

df[year_columns] = df[year_columns].apply(lambda row: row.fillna(row.mean()), axis=1)

In [626]:
missing_threshold = 0.5 * len(year_columns)
df = df.dropna(thresh=missing_threshold, axis=0)

In [627]:
df.shape

(20537, 39)

In [628]:
df.isnull().sum()

Country Name     0
Country Code     0
Series Name      0
Series Code      0
1989 [YR1989]    0
1990 [YR1990]    0
1991 [YR1991]    0
1992 [YR1992]    0
1993 [YR1993]    0
1994 [YR1994]    0
1995 [YR1995]    0
1996 [YR1996]    0
1997 [YR1997]    0
1998 [YR1998]    0
1999 [YR1999]    0
2000 [YR2000]    0
2001 [YR2001]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
dtype: int64

In [629]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989 [YR1989],1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,21.708333,21.708333,21.708333,21.708333,21.708333,21.708333,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,36.1
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,8.479167,8.479167,8.479167,8.479167,8.479167,8.479167,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,18.5
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,66.031250,66.031250,66.031250,66.031250,66.031250,66.031250,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,85.0
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,58.266667,58.266667,58.266667,58.266667,58.266667,58.266667,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,57.461905,57.461905,57.461905,57.461905,57.461905,57.461905,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,81.7

In [630]:
df.columns = [col.replace(" [YR", "_").replace("]", "") if "YR" in col else col for col in df.columns]

In [631]:
df.reset_index(drop=True, inplace=True)

In [632]:
df.head()

,Country Name,Country Code,Series Name,Series Code,1989_1989,1990_1990,1991_1991,1992_1992,1993_1993,1994_1994,...,2014_2014,2015_2015,2016_2016,2017_2017,2018_2018,2019_2019,2020_2020,2021_2021,2022_2022,2023_2023
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,21.708333,21.708333,21.708333,21.708333,21.708333,21.708333,...,26.1,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,36.1
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,8.479167,8.479167,8.479167,8.479167,8.479167,8.479167,...,10.2,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,18.5
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,66.031250,66.031250,66.031250,66.031250,66.031250,66.031250,...,78.0,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,85.0
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,58.266667,58.266667,58.266667,58.266667,58.266667,58.266667,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,57.461905,57.461905,57.461905,57.461905,57.461905,57.461905,...,86.5,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,81.7

In [633]:
df.shape

(20537, 39)

In [634]:
df.to_csv('../datasets/cleaned_dataset.csv')

In [635]:
# World Bank, 2025
# World Bank country classifications by income level for 2024-2025
# https://databank.worldbank.org/data/download/site-content/CLASS.xlsx

url = "https://databank.worldbank.org/data/download/site-content/CLASS.xlsx"

column_names = ["Country Name", "Country Code", "Region", "Income Level", "Lending Category", "Extra"]

income_df = pd.read_excel(url, sheet_name="List of economies", skiprows=3, header=None,  names=column_names)

In [636]:
income_df.head(100)

,Country Name,Country Code,Region,Income Level,Lending Category,Extra
0,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,NaN
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,NaN
2,Andorra,AND,Europe & Central Asia,High income,NaN,NaN
3,United Arab Emirates,ARE,Middle East & North Africa,High income,NaN,NaN
4,Argentina,ARG,Latin America & Caribbean,Upper middle income,IBRD,NaN
...,...,...,...,...,...,...
95,Jordan,JOR,Middle East & North Africa,Upper middle income,IBRD,NaN
96,Japan,JPN,East Asia & Pacific,High income,NaN,NaN
97,Kazakhstan,KAZ,Europe & Central Asia,Upper middle income,IBRD,NaN
98,Kenya,KEN,Sub-Saharan Africa,Lower middle income,Blend,NaN
99,Kyrgyz Republic,KGZ,Europe & Central Asia,Lower middle income,IDA,NaN

In [637]:
income_df = income_df[["Country Name", "Country Code", "Income Level"]]

In [638]:
growth_rates_emissions_energy_prod_income_level_country_df = df.merge(income_df, on=["Country Name", "Country Code"], how="left")

In [639]:
growth_rates_emissions_energy_prod_income_level_country_df.head()

,Country Name,Country Code,Series Name,Series Code,1989_1989,1990_1990,1991_1991,1992_1992,1993_1993,1994_1994,...,2015_2015,2016_2016,2017_2017,2018_2018,2019_2019,2020_2020,2021_2021,2022_2022,2023_2023,Income Level
0,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,21.708333,21.708333,21.708333,21.708333,21.708333,21.708333,...,27.6,28.8,30.3,31.4,32.6,33.8,34.9,36.1,36.1,NaN
1,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,8.479167,8.479167,8.479167,8.479167,8.479167,8.479167,...,11.4,12.6,13.5,14.5,15.6,16.4,17.4,18.5,18.5,NaN
2,Afghanistan,AFG,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,66.031250,66.031250,66.031250,66.031250,66.031250,66.031250,...,79.5,80.5,81.6,82.6,83.2,83.8,84.5,85.0,85.0,NaN
3,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,58.266667,58.266667,58.266667,58.266667,58.266667,58.266667,...,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3,NaN
4,Afghanistan,AFG,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,57.461905,57.461905,57.461905,57.461905,57.461905,57.461905,...,64.6,97.1,97.1,91.6,97.1,97.1,97.1,81.7,81.7,NaN

In [640]:
print(growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].value_counts())

Income Level
High income            5463
Upper middle income    4206
Lower middle income    4174
Low income             2000
Name: count, dtype: int64

In [641]:
missing_countries = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()]["Country Name"].unique()
print("Countries with missing income classification:", missing_countries)

Countries with missing income classification: ['Afghanistan' 'Aruba' "Cote d'Ivoire" 'Curacao' 'Czechia'
 'Sao Tome and Principe' 'Turkiye' 'Venezuela, RB' 'Viet Nam'
 'Africa Eastern and Southern' 'Africa Western and Central' 'Arab World'
 'Caribbean small states' 'Central Europe and the Baltics'
 'Early-demographic dividend' 'East Asia & Pacific'
 'East Asia & Pacific (excluding high income)'
 'East Asia & Pacific (IDA & IBRD countries)' 'Euro area'
 'Europe & Central Asia' 'Europe & Central Asia (excluding high income)'
 'Europe & Central Asia (IDA & IBRD countries)' 'European Union'
 'Fragile and conflict affected situations'
 'Heavily indebted poor countries (HIPC)' 'High income' 'IBRD only'
 'IDA & IBRD total' 'IDA blend' 'IDA only' 'IDA total'
 'Late-demographic dividend' 'Latin America & Caribbean'
 'Latin America & Caribbean (excluding high income)'
 'Latin America & the Caribbean (IDA & IBRD countries)'
 'Least developed countries: UN classification' 'Low & middle income'
 'Low income' 'Lower middle income' 'Middle East & North Africa'
 'Middle East & North Africa (excluding high income)'
 'Middle East & North Africa (IDA & IBRD countries)' 'Middle income'
 'North America' 'OECD members' 'Other small states'
 'Pacific island small states' 'Post-demographic dividend'
 'Pre-demographic dividend' 'Small states' 'South Asia'
 'South Asia (IDA & IBRD)' 'Sub-Saharan Africa'
 'Sub-Saharan Africa (excluding high income)'
 'Sub-Saharan Africa (IDA & IBRD countries)' 'Upper middle income' 'World']

In [642]:
regions_to_remove = [
    "World", "Sub-Saharan Africa", "OECD members", "East Asia & Pacific", "Europe & Central Asia",
    "Middle East & North Africa", "Latin America & Caribbean", "South Asia", "North America",
    "Fragile and conflict affected situations", "Least developed countries: UN classification",
    "Low & middle income", "Lower middle income", "Middle income", "Upper middle income",
    "Heavily indebted poor countries (HIPC)", "Small states", "IBRD only", "IDA & IBRD total",
    "IDA blend", "IDA only", "IDA total", "Euro area", "European Union",
    "East Asia & Pacific (IDA & IBRD countries)", "Europe & Central Asia (IDA & IBRD countries)",
    "Latin America & the Caribbean (IDA & IBRD countries)",
    "Middle East & North Africa (IDA & IBRD countries)", "Sub-Saharan Africa (IDA & IBRD countries)",
    "Africa Eastern and Southern", "Africa Western and Central", "Arab World", "Caribbean small states",
    "Central Europe and the Baltics", "Early-demographic dividend", "East Asia & Pacific (excluding high income)",
    "Europe & Central Asia (excluding high income)", "High income", "Late-demographic dividend",
    "Latin America & Caribbean (excluding high income)", "Low income", "Middle East & North Africa (excluding high income)",
    "Other small states", "Pacific island small states", "Post-demographic dividend",
    "Pre-demographic dividend", "South Asia (IDA & IBRD)", "Sub-Saharan Africa (excluding high income)"
]

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].isin(regions_to_remove)
]

print("Remaining unique countries:", growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].nunique())

Remaining unique countries: 217

In [643]:
missing_countries = growth_rates_emissions_energy_prod_income_level_country_df[
    growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()
]["Country Name"].unique()

print("Low/Middle-Income Countries with Missing Income Classification:", missing_countries)

Low/Middle-Income Countries with Missing Income Classification: ['Afghanistan' 'Aruba' "Cote d'Ivoire" 'Curacao' 'Czechia'
 'Sao Tome and Principe' 'Turkiye' 'Venezuela, RB' 'Viet Nam']

In [644]:
manual_income_levels = {
    "Cote d'Ivoire": "Lower middle income",
    "Sao Tome and Principe": "Lower middle income",
    "Turkiye": "Upper middle income",
    "Viet Nam": "Lower middle income",
    "Afghanistan": "Low income",
    "Venezuela, RB": "Not classified",
    "Aruba": "High income",
    "Curacao": "High income",
    "Czechia": "Not classified"   
}

growth_rates_emissions_energy_prod_income_level_country_df["Income Level"] = growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].map(manual_income_levels).fillna(growth_rates_emissions_energy_prod_income_level_country_df["Income Level"])

missing_countries_final = growth_rates_emissions_energy_prod_income_level_country_df[
    growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isna()
]["Country Name"].unique()

print("Final missing countries:", missing_countries_final)

Final missing countries: []

In [645]:
# Remove High income countries

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].isin(["High income", "Not classified"])
]

In [646]:
growth_rates_emissions_energy_prod_income_level_country_df.tail()

,Country Name,Country Code,Series Name,Series Code,1989_1989,1990_1990,1991_1991,1992_1992,1993_1993,1994_1994,...,2015_2015,2016_2016,2017_2017,2018_2018,2019_2019,2020_2020,2021_2021,2022_2022,2023_2023,Income Level
16482,Zimbabwe,ZWE,"Services, value added (annual % growth)",NV.SRV.TOTL.KD.ZG,2.766437,7.623569,5.084571,0.438988,0.631307,3.136767,...,3.533092,4.325045,5.606568,3.403563,-3.744143,-9.589924,7.701033,6.857145,6.676506,Lower middle income
16483,Zimbabwe,ZWE,Total greenhouse gas emissions excluding LULUC...,EN.GHG.TOT.ZG.AR5,-13.970193,-13.970193,-0.079189,2.626063,-10.494643,-13.065972,...,-12.060964,-17.297950,-18.811867,-12.927973,-17.405963,-22.060673,-15.924071,-13.166997,-13.166997,Lower middle income
16484,Zimbabwe,ZWE,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.MT.CE.AR5,31.132400,34.348000,34.320800,35.250000,30.743300,29.860100,...,30.205300,28.406500,27.886500,29.907500,28.369400,26.770600,28.878400,29.825400,31.019300,Lower middle income
16485,Zimbabwe,ZWE,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.PC.CE.AR5,3.155909,3.388285,3.298549,3.293561,2.830800,2.746224,...,2.097734,1.945612,1.882635,1.989264,1.857686,1.724145,1.828070,1.856077,1.898270,Lower middle income
16486,Zimbabwe,ZWE,Total greenhouse gas emissions including LULUC...,EN.GHG.ALL.LU.MT.CE.AR5,39.783038,39.783038,39.783038,39.783038,39.783038,39.783038,...,46.476300,44.677500,44.157500,46.178500,44.640400,43.041600,39.783038,39.783038,39.783038,Lower middle income

In [647]:
growth_rates_emissions_energy_prod_income_level_country_df['Income Level'].value_counts()

Income Level
Lower middle income    4417
Upper middle income    4294
Low income             2070
Name: count, dtype: int64

In [648]:
growth_rates_emissions_energy_prod_income_level_country_df.shape

(10781, 40)

In [649]:
growth_rates_emissions_energy_prod_income_level_country_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10781 entries, 0 to 16486
Data columns (total 40 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  10781 non-null  object
 1   Country Code  10781 non-null  object
 2   Series Name   10781 non-null  object
 3   Series Code   10781 non-null  object
 4   1989_1989     10781 non-null  float64
 5   1990_1990     10781 non-null  float64
 6   1991_1991     10781 non-null  float64
 7   1992_1992     10781 non-null  float64
 8   1993_1993     10781 non-null  float64
 9   1994_1994     10781 non-null  float64
 10  1995_1995     10781 non-null  float64
 11  1996_1996     10781 non-null  float64
 12  1997_1997     10781 non-null  float64
 13  1998_1998     10781 non-null  float64
 14  1999_1999     10781 non-null  float64
 15  2000_2000     10781 non-null  float64
 16  2001_2001     10781 non-null  float64
 17  2002_2002     10781 non-null  float64
 18  2003_2003     10781 non-null  float64
 19  2004_2004     10781 non-null  float64
 20  2005_2005     10781 non-null  float64
 21  2006_2006     10781 non-null  float64
 22  2007_2007     10781 non-null  float64
 23  2008_2008     10781 non-null  float64
 24  2009_2009     10781 non-null  float64
 25  2010_2010     10781 non-null  float64
 26  2011_2011     10781 non-null  float64
 27  2012_2012     10781 non-null  float64
 28  2013_2013     10781 non-null  float64
 29  2014_2014     10781 non-null  float64
 30  2015_2015     10781 non-null  float64
 31  2016_2016     10781 non-null  float64
 32  2017_2017     10781 non-null  float64
 33  2018_2018     10781 non-null  float64
 34  2019_2019     10781 non-null  float64
 35  2020_2020     10781 non-null  float64
 36  2021_2021     10781 non-null  float64
 37  2022_2022     10781 non-null  float64
 38  2023_2023     10781 non-null  float64
 39  Income Level  10781 non-null  object
dtypes: float64(35), object(5)
memory usage: 3.4+ MB

In [650]:
growth_rates_emissions_energy_prod_income_level_country_df.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Series Code     0
1989_1989       0
1990_1990       0
1991_1991       0
1992_1992       0
1993_1993       0
1994_1994       0
1995_1995       0
1996_1996       0
1997_1997       0
1998_1998       0
1999_1999       0
2000_2000       0
2001_2001       0
2002_2002       0
2003_2003       0
2004_2004       0
2005_2005       0
2006_2006       0
2007_2007       0
2008_2008       0
2009_2009       0
2010_2010       0
2011_2011       0
2012_2012       0
2013_2013       0
2014_2014       0
2015_2015       0
2016_2016       0
2017_2017       0
2018_2018       0
2019_2019       0
2020_2020       0
2021_2021       0
2022_2022       0
2023_2023       0
Income Level    0
dtype: int64

In [651]:
growth_rates_emissions_energy_prod_income_level_country_df['Income Level'].value_counts()

Income Level
Lower middle income    4417
Upper middle income    4294
Low income             2070
Name: count, dtype: int64

In [652]:
unique_country_count = growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].nunique()
print(f"Final unique country count: {unique_country_count}")

Final unique country count: 136

In [653]:
duplicates = growth_rates_emissions_energy_prod_income_level_country_df.duplicated()
assert duplicates.sum() == 0, f"Found {duplicates.sum()} duplicate rows!"
print("No duplicate rows found.")

No duplicate rows found.

In [654]:
valid_income_levels = ["Low income", "Lower middle income", "Upper middle income"]
unique_income_levels = growth_rates_emissions_energy_prod_income_level_country_df["Income Level"].unique()

assert all(income in valid_income_levels for income in unique_income_levels), "There are invalid income levels in the dataset!"
print("Only low, lower middle, and upper middle income countries remain.")

Only low, lower middle, and upper middle income countries remain.

In [655]:
country_check = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].isin(["Bulgaria", "Palau", "Russian Federation"])]

country_check.tail()

,Country Name,Country Code,Series Name,Series Code,1989_1989,1990_1990,1991_1991,1992_1992,1993_1993,1994_1994,...,2015_2015,2016_2016,2017_2017,2018_2018,2019_2019,2020_2020,2021_2021,2022_2022,2023_2023,Income Level
12417,Russian Federation,RUS,"Services, value added (annual % growth)",NV.SRV.TOTL.KD.ZG,1.233421,1.233421,-2.572343,-8.430042,-19.479535,-2.484876,...,-2.052879,-0.421167,1.888011,2.806935,2.447491,-2.159233,7.027743,-2.318846,-2.318846,Upper middle income
12418,Russian Federation,RUS,Total greenhouse gas emissions excluding LULUC...,EN.GHG.TOT.ZG.AR5,-25.184024,-25.184024,-2.306116,-10.204190,-17.845208,-25.657064,...,-26.358099,-26.707031,-25.035248,-21.665622,-19.012398,-21.857376,-16.888202,-14.488662,-14.488662,Upper middle income
12419,Russian Federation,RUS,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.MT.CE.AR5,2874.962400,3065.696400,2994.997900,2752.866900,2518.616500,2279.128700,...,2257.637100,2246.939900,2298.191700,2401.494200,2482.834000,2395.615600,2547.955400,2621.518000,2672.039400,Upper middle income
12420,Russian Federation,RUS,Total greenhouse gas emissions excluding LULUC...,EN.GHG.ALL.PC.CE.AR5,19.462110,20.718448,20.182713,18.533057,16.965090,15.357191,...,15.608586,15.494485,15.817607,16.516681,17.069631,16.493602,17.602849,18.175081,18.578261,Upper middle income
12421,Russian Federation,RUS,Total greenhouse gas emissions including LULUC...,EN.GHG.ALL.LU.MT.CE.AR5,1606.887281,1606.887281,1606.887281,1606.887281,1606.887281,1606.887281,...,1629.130100,1600.405300,1655.343100,1766.642700,1881.351100,1790.821600,1606.887281,1606.887281,1606.887281,Upper middle income

In [656]:
# This year, three countries—Bulgaria, Palau, and Russia—moved from the upper-middle-income to the high-income category (World Bank, 2025)
# World Bank country classifications by income level for 2024-2025
# https://blogs.worldbank.org/en/opendata/world-bank-country-classifications-by-income-level-for-2024-2025
# Remove Bulgaria, Palau, Russian Federation

growth_rates_emissions_energy_prod_income_level_country_df = growth_rates_emissions_energy_prod_income_level_country_df[
    ~growth_rates_emissions_energy_prod_income_level_country_df["Country Name"].isin(["Bulgaria", "Palau", "Russian Federation"])
]

In [657]:
country_check = growth_rates_emissions_energy_prod_income_level_country_df[growth_rates_emissions_energy_prod_income_level_country_df[
    "Country Name"
].isin(["Bulgaria", "Palau", "Russian Federation"])]

country_check.head()

Empty DataFrame
Columns: [Country Name, Country Code, Series Name, Series Code, 1989_1989, 1990_1990, 1991_1991, 1992_1992, 1993_1993, 1994_1994, 1995_1995, 1996_1996, 1997_1997, 1998_1998, 1999_1999, 2000_2000, 2001_2001, 2002_2002, 2003_2003, 2004_2004, 2005_2005, 2006_2006, 2007_2007, 2008_2008, 2009_2009, 2010_2010, 2011_2011, 2012_2012, 2013_2013, 2014_2014, 2015_2015, 2016_2016, 2017_2017, 2018_2018, 2019_2019, 2020_2020, 2021_2021, 2022_2022, 2023_2023, Income Level]
Index: []

[0 rows x 40 columns]

In [658]:
growth_rates_emissions_energy_prod_income_level_country_df.shape

(10533, 40)

In [659]:
growth_rates_emissions_energy_prod_income_level_country_df.isnull().sum()

Country Name    0
Country Code    0
Series Name     0
Series Code     0
1989_1989       0
1990_1990       0
1991_1991       0
1992_1992       0
1993_1993       0
1994_1994       0
1995_1995       0
1996_1996       0
1997_1997       0
1998_1998       0
1999_1999       0
2000_2000       0
2001_2001       0
2002_2002       0
2003_2003       0
2004_2004       0
2005_2005       0
2006_2006       0
2007_2007       0
2008_2008       0
2009_2009       0
2010_2010       0
2011_2011       0
2012_2012       0
2013_2013       0
2014_2014       0
2015_2015       0
2016_2016       0
2017_2017       0
2018_2018       0
2019_2019       0
2020_2020       0
2021_2021       0
2022_2022       0
2023_2023       0
Income Level    0
dtype: int64

In [660]:
growth_rates_emissions_energy_prod_income_level_country_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10533 entries, 0 to 16486
Data columns (total 40 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  10533 non-null  object
 1   Country Code  10533 non-null  object
 2   Series Name   10533 non-null  object
 3   Series Code   10533 non-null  object
 4   1989_1989     10533 non-null  float64
 5   1990_1990     10533 non-null  float64
 6   1991_1991     10533 non-null  float64
 7   1992_1992     10533 non-null  float64
 8   1993_1993     10533 non-null  float64
 9   1994_1994     10533 non-null  float64
 10  1995_1995     10533 non-null  float64
 11  1996_1996     10533 non-null  float64
 12  1997_1997     10533 non-null  float64
 13  1998_1998     10533 non-null  float64
 14  1999_1999     10533 non-null  float64
 15  2000_2000     10533 non-null  float64
 16  2001_2001     10533 non-null  float64
 17  2002_2002     10533 non-null  float64
 18  2003_2003     10533 non-null  float64
 19  2004_2004     10533 non-null  float64
 20  2005_2005     10533 non-null  float64
 21  2006_2006     10533 non-null  float64
 22  2007_2007     10533 non-null  float64
 23  2008_2008     10533 non-null  float64
 24  2009_2009     10533 non-null  float64
 25  2010_2010     10533 non-null  float64
 26  2011_2011     10533 non-null  float64
 27  2012_2012     10533 non-null  float64
 28  2013_2013     10533 non-null  float64
 29  2014_2014     10533 non-null  float64
 30  2015_2015     10533 non-null  float64
 31  2016_2016     10533 non-null  float64
 32  2017_2017     10533 non-null  float64
 33  2018_2018     10533 non-null  float64
 34  2019_2019     10533 non-null  float64
 35  2020_2020     10533 non-null  float64
 36  2021_2021     10533 non-null  float64
 37  2022_2022     10533 non-null  float64
 38  2023_2023     10533 non-null  float64
 39  Income Level  10533 non-null  object
dtypes: float64(35), object(5)
memory usage: 3.3+ MB

In [661]:
growth_rates_emissions_energy_prod_income_level_country_df.to_csv('../datasets/growth_rates_emissions_energy_prod_income_level_country_df.csv')

print("Merged Dataset with only Low, Lower middle, Upper income level countries saved successfully")

Merged Dataset with only Low, Lower middle, Upper income level countries saved successfully